package vpn

var (
	ST_NOTHING              = 0
	ST_CONTROL_CHANNEL_OPEN = 1
	ST_CONTROL_MESSAGE_SENT = 2
	ST_KEY_EXCHANGED        = 3
	ST_PULL_REQUEST_SENT    = 4
	ST_OPTIONS_PUSHED       = 5
	ST_INITIALIZED          = 6
)
