name: build

on: push

jobs:
  short-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Run short tests
      run: go test --short -cover ./vpn

  gosec:
    runs-on: ubuntu-latest
    env:
        GO111MODULE: on
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
    - name: Run Gosec security scanner
      uses: securego/gosec@master
      with:
        args: '-no-fail ./...'

  coverage-threshold:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
    - name: Ensure coverage threshold
      run: make test-coverage-threshold

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: run integration tests
        run: go test -v ./tests/integration

