name: build
# this action is covering internal/ tree with go1.20

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  short-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Run short tests
      run: go test --short -cover ./internal/...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Lint with revive action, from pre-built image
      uses: docker://morphy/revive-action:v2
      with:
        path: "internal/..."

  gosec:
    runs-on: ubuntu-latest
    env:
        GO111MODULE: on
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Run Gosec security scanner
      uses: securego/gosec@master
      with:
        args: '-no-fail ./...'

  coverage-threshold:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'
    - name: Ensure coverage threshold
      run: make test-coverage-threshold

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - name: run integration tests
        run: go run ./tests/integration

